### PR TITLE
Use glow as iced backend

### LINKED ISSUE #60: use glow backend instead of wgpu
wgpu force user to install vulkan driver.
glow may be a solution: https://github.com/hecrj/iced/issues/613#issuecomment-725550260
We will lost svg and qr_code features but we may be able to replace them with png and iced Image

### PR DESCRIPTION
**Pull request by edouardparis**
wgpu required vulkan drivers to be installed.
glow does not have this requirement, but does not
support yet iced features like svg.

closes #60

### CODE REVIEW

**Comment by darosior** [comment]
Cool! Can we get around the svg limitation by using font icons? Maybe for the Qr too

**Comment by edouardparis** [comment]
Yes, Font icons are supported, but the result will have certainly only one color.

**Comment by edouardparis** [comment]
Failed to use font icon for the logo, still investigating but i prefer to not spend more time on it

**Review by danielabrozzoni — APPROVED** [review]
ACK fc47f86487af422ad5e34ce1a52a727a07d54b6e

**Comment by darosior** [comment]
Just to make it clear here too: i want to keep this on hold until we are clear it's the right path.

**Pull request closed without merging**
