### PR TITLE
Update revaultd config: add scripts config

### PR DESCRIPTION
**Pull request by edouardparis**
Need  https://github.com/revault/revaultd/pull/210

### CODE REVIEW

**Comment by danielabrozzoni** [comment]
That was quick :)
Settings are a bit broken now:
Revault GUI_035

I'm wondering if we should display the descriptors or not in the settings... Are they useful to the user?

**Comment by edouardparis** [comment]
I am ok to display them, so user can maybe import them somewhere else or compare them with an other user.

**Comment by danielabrozzoni** [comment]
I would put the `deposit_descriptor:` etc in smaller, maybe same size as `Cosigners`?
Also, please use the capital letter and avoid the `:`: `Deposit descriptor`

Also notice that the descriptors are a bit trimmed on the right

**Review by danielabrozzoni — CHANGES_REQUESTED** [review]
As specified above :)

**Comment by edouardparis** [comment]
2021-05-10T15:33:02,100236997+02:00
As you said descriptors are trimmed, we may wait for the horizontal scroll or change later the whole settings panel.
But for now we need this fix to be compliant with the revaultd new config.
Thanks for the test :+1:

**Pull request merged**
