### PR TITLE
Display real spend amount, without considering change and cpfp

### PR DESCRIPTION
**Pull request by danielabrozzoni**
To be tested with https://github.com/revault/revaultd/pull/218

### CODE REVIEW

**Comment by danielabrozzoni** [comment]
Not anymore priority, feel free to ignore this MR

**Comment by danielabrozzoni** [comment]
https://github.com/revault/revaultd/pull/218 is merged, this MR still works (:tada:), ready for review :D

**Comment by edouardparis** [comment]
We display real spend amount, which is really better that what we have previously but we do not include the fees.
maybe we can add a line with the fees. (with fees: total vaults amount - change output amount - txs output amounts)
like
---------------------------------------
txid:.....       1 BTC
                   fees: 0,00044512  
---------------------------------------

**Comment by danielabrozzoni** [comment]
You're right, this is related to #73. I can add that field for now, but I think we should display the unvault fees as well...

**Comment by edouardparis** [comment]
the unvault fees are included by: total vaults amount - change output amount - txs output amounts

**Comment by danielabrozzoni** [comment]
Ah, right! :)

**Comment by darosior** [comment]
> the unvault fees are included in: fees = total vaults amount - change output amount - txs output amounts

I think we should take the CPFPs into account as well, see https://github.com/revault/revault-gui/issues/73#issuecomment-864179619 .

**Comment by danielabrozzoni** [comment]
Just pushed a commit which adds the fee amount in the home. I don't really like the solution I found, suggestions are accepted :)

Note that it is different from the fee amount displayed in the spend screen, that doesn't take the unvault fees into account (this needs to be fixed, but in a following PR)

**Comment by edouardparis** [comment]
> Note that it is different from the fee amount displayed in the spend screen, that doesn't take the unvault fees into account (this needs to be fixed, but in a following PR)

It's the cpfp output which is not included
2021-06-25T10:59:54,922785096+02:00
2021-06-25T11:00:04,103396317+02:00

the unvault fees are taken into account in the fees :)

**Review by edouardparis — APPROVED** [review]
ACK  dfd78054e4bfa52310adf2c8abcc9aba111cc2c6

**Pull request merged**
