### PR TITLE
Rework settings panel 🎉 

### PR DESCRIPTION
**Pull request by danielabrozzoni**
Needs https://github.com/revault/revaultd/pull/256

Stakeholder view:
Revault GUI_097
Revault GUI_098

(Sadly watchtowers are always dead 🤷🏻‍♀️)

Manager view:
Revault GUI_099
Revault GUI_100

### CODE REVIEW

**Comment by darosior** [comment]
Wow this looks much better, just looking at the screenshots!

A nit: i'm not sure we should display the Emergency address. With it a manager could blackmail the stakeholders (cause he would have the signatures already). I know it's technically accessible on the "non-trusted" (:tm:) laptop but displaying it makes the matter worse imho.

**Comment by danielabrozzoni** [comment]
Do you think that my xpub should be displayed? Is it useful information to have? If not, we could ditch the whole "My information" card altogether...

**Comment by darosior** [comment]
When in doubt, i'd say print less technical (confusing) stuff :)
‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by danielabrozzoni** [comment]
Updated to reflect changes in https://github.com/revault/revaultd/pull/256

**Comment by edouardparis** [comment]
works great.
I am thinking that maybe we should label the cosigner that the stakeholder manage but we change that later
ACK 7f0da99e337b234b982c8fe716417495a654d088

**Comment by danielabrozzoni** [comment]
Sadly only the managers see the cosigners :( I would love to label them (at least with the bitcoin public key) but it wasn't trivial...

**Pull request merged**
