### PR TITLE
Add network flag to args

### LINKED ISSUE #188: `--datadir <existing testnet datadir>` will launch the installer
It should just launch the GUI with the existing datadir.

### PR DESCRIPTION
**Pull request by edouardparis**
close #188

### CODE REVIEW

**Comment by danielabrozzoni** [comment]
Can you document the network flag somewhere? I think we should have all the possible flags in the README, and maybe the demo docs will need to be updated.

I'm not sure if this is the right direction tbh. It feels a bit weird to have `conf`, `datadir` and `network`, but if you like it I'm ok with that

**Comment by edouardparis** [comment]
I does not break the process of the DEMO with this branch and DEMO specifies to use 0.2 release

Because we want to enable multiple network setup in a datadir, a flag network was necessary to make explicit wich setup the user want to use or install in a datadir.
We keep the `--conf` flag in order to have an alternative way to run a setup if it exists or get an error if it does not without launching the installer.

**Review by danielabrozzoni — APPROVED** [review]
Yeah I see the motivation behind this :)

utACK b3ff45888fdc874993c120dccec0ddb47491d4ca

**Pull request merged**
