### PR TITLE
Refac UI app modules

### PR DESCRIPTION
**Pull request by edouardparis**
based on #120

### CODE REVIEW

**Comment by danielabrozzoni** [comment]
Please rebase :)

**Review by danielabrozzoni — APPROVED** [review]
utACK d020db1b4257046b07b80a413ffb2ac7f9522990

**Comment by danielabrozzoni** [comment]
utACK 2dfbbab

**Comment by edouardparis** [comment]
ACK 2dfbbabbde6bf22660b7e2e55bf6dcf761bf4669

**Pull request merged**
